version: '3.8'
services:
  seunswap_v1:
    image: postgres:14.0-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=seunswap_db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql

  app:
    depends_on:
      - seunswap_v1
    build: .
    restart: on-failure
    ports:
      - "8100:8100"
    stdin_open: true
    tty: true

volumes:
  db: